# ===============================
# Application
# ===============================
spring.application.name=smart-recruitment-engine

# ===============================
# MySQL Datasource
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/smart_recruitment_engine?createDatabaseIfNotExist=false&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Ankit#@9876
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# JWT
# ===============================
jwt.secret=my-very-very-highly-secure-secret-key-which-no-has-access-to
jwt.expiration-ms=14400000